### ISSUE TITLE
Alfresco 7.4+ compatibility (log4j)

### ISSUE THREAD

**Issue by DejmalDavid** [softwareloop/uploader-plus#152]
Starting from ACS 7.4, log4jv2 is used in Alfresco. On start Alfresco i get this error:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webscript.com.softwareloop.uploader-plus.list-content-types.get' defined in class path resource [alfresco/module/uploader-plus-repo/context/webscript-context.xml]: Bean instantiation via constructor failed; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Logger`

**Comment by abhinavmishra14** [comment]
Try this version updated for ACS6.x and later. If slf4j api is used instead, it wouldn’t cause the issue you are facing.

https://github.com/abhinavmishra14/uploader-plus/releases/tag/v1.8

I have a PR here as well: https://github.com/softwareloop/uploader-plus/pull/151

**Comment by DejmalDavid** [comment]
Yes it working with alfresco 7.4. Thanks
